# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Express a "workflow": a collection of CI "jobs" ("build", "test", "deploy", etc.) which are run in a specified order. 
# This workflow executes a build job, a job that runs tests, and a deploy job sequentially.  The deploy job is commented out to avoid a bad deployment.
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
      - run-tests:
          requires:
            - build
#      - deploy:
#          requires:
#            - run-tests 

# "build" job template: (job is a collection of steps that are executed as a single unit in an execution environment)
#scott's feedback: Minor point, but we may need to be a bit careful with where we put the build job stub and how we frame it with comments. E.g. sometimes you have to build in order to run tests, but sometimes you only have to build in preparation for deploying. So build → test makes sense in some cases but test → build makes sense in others.
#I don’t think we need to make the fallback super complicated to handle all possible situations or anything like that. But I think it’s worth thinking about how to make the job order and explanatory comments as clear and helpful as we can given that there are multiple reasonably common cases.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. 
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable

    # Add steps to the job.  Steps are ...
    steps:
      - checkout
      - run:
          name: "build"
          command: "echo replace this echo with the command to build your application"
  
  #Job where tests are run
  run-tests:
      # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
      # See: https://circleci.com/docs/configuration-reference/#executor-job
      docker:
        - image: cimg/base:stable
      # Add steps to the job
      # See: https://circleci.com/docs/configuration-reference/#steps
      steps:
        - checkout
        - run:
            name: "run tests"
            command: |
              mkdir test-results
              "echo replace this echo command with your test command" 
      
      # Use https://circleci.com/docs/collect-test-data/ to upload test results to CircleCI to easily visualize test feailures
      #  - store_test_results:
      #      path: test-results 

#Deploy job 
 # deploy:
 #     docker:
 #       - image: cimg/deploy:2023.05
 #     steps:
 #       - checkout
 #       - run:
 #           name: "deploy"
 #           command: "echo replace this echo command with your deploy command"


